### ISSUE TITLE
Switch with css / sass / scss file too

### ISSUE THREAD

**Issue by DavidBabel** [infinity1207/angular2-switcher#1]
Amazing extension but i got a feature request. Can you consider adding another shortcut (close to alt+o) for switching with .css or .sass or .scss coresponding file ? 

This extension could become a must have

**Comment by infinity1207** [comment]
Thank you for your feedback, you will have it in next version.

**Comment by DavidBabel** [comment]
Perfect ! I don't know if it's already the case, but a way to configurate the shortcut may be awesome.

Thanks for your fast answer

**Comment by DavidBabel** [comment]
A good way can be this : 

**alt+o :** 
if on ts : go to html
if on css : go to html
if on html: go to previous (ts or css)

**alt+i :** 
if on ts : go to css
if on html : go to css
if on css: go to previous (ts or html)

**alt+u :** 
if on ts : go to css
if on html : go to css
if on ts: go to previous (css or html)

**Comment by infinity1207** [comment]
@DavidBabel thanks for you good suggestion. and i will implement it. i think you maybe wrote a mistack about `alt+u`, so the final result is:

alt+o :
if on ts : go to html
if on css : go to html
if on html: go to previous (ts or css)

alt+i :
if on ts : go to css
if on html : go to css
if on css: go to previous (ts or html)

alt+u :
if on css : go to ts
if on html : go to ts
if on ts: go to previous (css or html)

**Comment by DavidBabel** [comment]
Exact, i made a mistake. I just give a try to your extension, it's a really great job. Thanks for your reactivity
