### ISSUE TITLE
Add the possibility to switch to the .spec.ts unit test file associated with the .ts file

### ISSUE THREAD

**Issue by matproulx** [infinity1207/angular2-switcher#14]
It would be cool to add the possibility to switch to associated .spec.ts (unit test) file of a .ts file

**Comment by gdlm91** [comment]
+1... This will be very helpful!!

**Comment by gdlm91** [comment]
There seems to be a commit to support switching to .spec files here : 

https://github.com/infinity1207/angular2-switcher/commit/c7577dc5f3d31e5b8e788e8dddf1b4fe87991aa5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33

The keybindings is **shift+alt+p** ...

**Comment by matproulx** [comment]
Yeah but how to install this version in Visual Studio Code ?
