### ISSUE TITLE
Not working since 0.15

### ISSUE THREAD

**Issue by lukgri** [infinity1207/angular2-switcher#16]
Hey,
the extension is not working at all since the 0.15 update on
macOS High Sierra Version 10.13.2,
Code 1.19.3 (1.19.3).

Description: nothing happens after pressing the combination.

I have checked if there is no duplicate keybind causing it to get ignored, restarted vs code & mac several times, no effect.

**Comment by Crazybutch** [comment]
I've had the same problem so i switched back to 0.1.4.

https://infinity1207.gallery.vsassets.io/_apis/public/gallery/publisher/infinity1207/extension/angular2-switcher/0.1.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage <- Remove Package from File Extension after download

Don't forget to set "extensions.autoUpdate": false" in User Settings -> CTRL + ;

**Comment by lukgri** [comment]
@Crazybutch thanks for the temp fix

**Comment by krosullivan** [comment]
Same. Getting `command 'extension.switchStyle' not found` doing `shift+alt+o` when I reinstall the extension

**Comment by infinity1207** [comment]
@krosullivan @lukgri @Crazybutch I just test in windows 10, so you are all in macOS?

**Comment by Crazybutch** [comment]
@infinity1207 I'm using Windows 10 (1709), Visual Studio Code 1.19.3
Had the same Problems with TypeScript Hero (had to downgrade)

**Comment by krosullivan** [comment]
Yeah, I'm osx. Exact same versions for everything  as @lukgri

**Comment by lukgri** [comment]
@infinity1207 yes, mac os

**Comment by infinity1207** [comment]
@lukgri @krosullivan @Crazybutch @MonsieurMan sorry about it, i have resolved this issue, please try it on 0.1.6.

**Comment by krosullivan** [comment]
Fixed! Thanks very much.

**Comment by lukgri** [comment]
can confirm, works like a charm - thank you!

**Comment by Crazybutch** [comment]
0.1.6 Fix confirmed ;)
