### ISSUE TITLE
Any way to get this working with Pug files?

### ISSUE THREAD

**Issue by koi-hime** [infinity1207/angular2-switcher#16]
I'm using Pug over HTML files, so I was wondering if there's a way to have it switch to Pug files instead of HTML files?

**Comment by infinity1207** [comment]
@n7commanderjohn Now you can config `angular2-switcher.templateFormats` to support Pug files.
### example:
```json
"angular2-switcher.templateFormats": [".pug"]
```

**Comment by koi-hime** [comment]
Great, thanks!
