### ISSUE TITLE
good done for the tool, I have another question

### ISSUE THREAD

**Issue by wenbaofu** [infinity1207/angular2-switcher#2]
I find typing the code in the html is very slow, your tool can imporve the speed for typing the val in html which defined in ts file, like *ngIf which defined in angular core, it can also give the auto-complete

**Comment by infinity1207** [comment]
@wenbaofu I have same trouble, you can try ![Angular 2 TypeScript Snippets](https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2#review-details).

**Comment by wenbaofu** [comment]
@infinity1207 ：I had intalled,in ts file work fine,but html file can not....

**Comment by infinity1207** [comment]
@wenbaofu if you installed Angular 2 TypeScript Snippets. Please try to type ng2- in html, and you will have HTML Snippets.

**Comment by wenbaofu** [comment]
@infinity1207 I know what you mean, in ts and html when type in ng2, vscode can give the tips,but I hope I can get the properties or variable which declared in ts file or in html file.
ex:
<form *ngIf="contacts" (ngSubmit)="**onSubmit()**" #**contactForm**="ngForm">
onSubmit() define in ts file,contactForm define in html file,when I code in html, when I type in on or con,
it can give the auto-complete

**Comment by infinity1207** [comment]
@wenbaofu I known you mean, sounds a bit difficult, but worth a shot.

**Comment by DavidBabel** [comment]
Seems to be a different kind a feature. I recommand you to separate the projects, since some people may not enjoy some part of the app, an renounce to it entirely

**Comment by infinity1207** [comment]
@DavidBabel i added a interesting feature at 0.1.0, now you can jump to the definition of variables/functions when press `f12` within html.

**Comment by DavidBabel** [comment]
Very interesting, Will try that today
