### ISSUE TITLE
F12 open 2 definitions like Peek view

### ISSUE THREAD

**Issue by Borongaj** [infinity1207/angular2-switcher#2]
When extension is installed, pressing F12 open the correct file, but with peek view opened (2 definitions found).

**Comment by grass29** [comment]
This seems to be related to this bug:
https://github.com/Microsoft/vscode/issues/63895

This issue is reproducible when "Angular Language Service" and "angular2-switcher" are enabled at the same time. They both contribute the go to definition functionality and hence the duplicates.

**Comment by AndreiToroplean** [comment]
> This issue is reproducible when "Angular Language Service" and "angular2-switcher" are enabled at the same time. They both contribute the go to definition functionality and hence the duplicates.

I am still getting this bug, and the issue for the "bug" you mentionned was closed as working "as intended".
