### ISSUE TITLE
Typescript & styles switching not working

### ISSUE THREAD

**Issue by armoucar** [infinity1207/angular2-switcher#20]
VsCode popup error: `command 'extension.switchTS' not found`.

Keyboard shortcut mappings:
```
{
  "key": "shift+alt+o",
  "command": "extension.switchTemplate"
},
{
  "key": "shift+alt+i",
  "command": "extension.switchStyle"
}
```

**Comment by Nastaliss** [comment]
@armoucar I'm getting the exact same error.
Switching to ts is impossible with **alt+u** but it correctly switches back from any other format to ts (using **alt+i** from styles for example).

**Comment by joekaiser** [comment]
`alt+o` `alt+i` `alt+p` are working for me, but `alt+u` stopped working today :/ (version 0.3)

**Comment by randallmeeker** [comment]
same here with 3.0 release it looks like?


Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-1066-oem snap

Name: angular2-switcher
Id: infinity1207.angular2-switcher
Description: Easily navigate to `typescript`|`template`|`style` in angular2 project.
Version: 0.3.0
Publisher: infinity1207
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=infinity1207.angular2-switcher

**Comment by infinity1207** [comment]
I'm sorry about this issue. Please try new version!

**Comment by joekaiser** [comment]
it is working again! thank you for the quick fix
