### ISSUE TITLE
Switch to style file not working

### ISSUE THREAD

**Issue by juninhocruzg3** [infinity1207/angular2-switcher#22]
Switch to TS File through `alt+u` and to HTML file by `alt+o` works fine. But I can't switch to style file through `alt+i`.
If I'm editing style and I press `alt+{u|o|p}`, it works. But I can't return to style file pressing `alt+i`.
No log error is showing.

I had same problem in my work computer and in my pc.

Ubuntu 19.04 and Debian 9.12
Both uses Code 1.43.0-insider
Angular2-Switcher 0.3.2

![Screenshot at 2020-02-13 12-34-24](https://user-images.githubusercontent.com/9886017/74456554-644e4e80-4e5d-11ea-9a37-6ff605bf0df4.png)

**Comment by Hitsu91** [comment]
I've got the same problem.

**Comment by jrstrayhorn** [comment]
i'm experiencing the same issue as well.

Using VS Code Version: 1.42.0
![image](https://user-images.githubusercontent.com/21061492/75034895-3203a900-547c-11ea-91a2-0c88a3f909f8.png)

**Comment by WayneChang** [comment]
![image](https://user-images.githubusercontent.com/60455514/75104518-f10ac080-5644-11ea-8ec6-2555fb30099e.png)
I've got the same issue.

**Comment by brianrichardson-dev** [comment]
Same here

![image](https://user-images.githubusercontent.com/39654350/76264927-661eee00-6220-11ea-971f-b3ab59c40649.png)

**Comment by Sgt-Nukem** [comment]
Is this a regression or some change in the vs-code host?

It worked fantastic for a long time and just ceased to work some weeks ago!

**Comment by infinity1207** [comment]
@juninhocruzg3 @Hitsu91 @jrstrayhorn @WayneChang @Borderlander103 
Sorry about that, Today i upgrade my vscode to 1.43.0(system setup), but all going well.
So i wondering which style(*.scss/*.sass/*.css/*.less/*.css) are you used.

**Comment by infinity1207** [comment]
Maybe you can check if there have keybinding confilicts.
![shortcuts](https://user-images.githubusercontent.com/9922916/77167024-314c4a00-6af0-11ea-969d-91a8aaf47b93.gif)

**Comment by juninhocruzg3** [comment]
@infinity1207, this issue occurs only SASS style for me. CSS and SCSS work fine here. No keybinding confilicts.

**Comment by infinity1207** [comment]
@jrstrayhorn Thanks for your feedback, I resolved this issue, Please try the newest version.

**Comment by WayneChang** [comment]
The issue is fixed after I upgrade vscode 1.43.

**Comment by juninhocruzg3** [comment]
Fixed for me. vscode 1.44-insiders.

Thanks!

**Comment by jrstrayhorn** [comment]
yup working for me as well!
