### ISSUE TITLE
Possibility of opening the .ts|.html|.css|.spec.ts file as a new tab

### ISSUE THREAD

**Issue by pascaljr** [infinity1207/angular2-switcher#4]
Often times, instead of switching from the ts to the html of my component in the same tab (changing the opened file), I prefer to open a new tab with the file opened there. It would be nice to have this as an optional behavior.

**Comment by maxaxehax** [comment]
Just a suggestion: if you disable preview editors (VS Code setting: `"workbench.editor.enablePreview": false`), you can achieve this exact behaviour.

**Comment by pascaljr** [comment]
I just found out about this yesterday. Indeed, it solves the problem. Thank you very much for the reply
