### ISSUE TITLE
alt-u doesnt work in MacOSX Sierra (v0.0.6)

### ISSUE THREAD

**Issue by exedmg** [infinity1207/angular2-switcher#4]
I've tried the alt+u shortcut but it doesnt  work in macosx (from css, html nor ts files). I use VSCode v 1.7.2 and MacOS Sierra. Am I missing something?

**Comment by infinity1207** [comment]
@exedmg other shortcuts (alt+o, alt+i) are ok?

**Comment by DavidBabel** [comment]
Works for me with your exact same config, seems to be a conflict with another extension.
Try to redefine manually the binds link in package.json : https://github.com/infinity1207/angular2-switcher/blob/master/package.json#L36

**Comment by infinity1207** [comment]
i just tried in Mac, this problem does exist. 
[Option key](https://en.wikipedia.org/wiki/Option_key)
