### ISSUE TITLE
Feature: ability to config file extensions

### ISSUE THREAD

**Issue by egozavr** [infinity1207/angular2-switcher#5]
Hi! In our project we use [PugJS](https://pugjs.org/api/getting-started.html) for templates. I would like to have an ability to switch to `.pug` file with `Alt+o` instead of `.html`.

**Comment by infinity1207** [comment]
@egozavr  Now you can config `angular2-switcher.templateFormats` to support Pug files.
### example:
```json
"angular2-switcher.templateFormats": [".pug"]
```
