### ISSUE TITLE
'alt + o' stopped working

### ISSUE THREAD

**Issue by tomasro27** [infinity1207/angular2-switcher#6]
Hi again, 
Thanks for adding .less support.  It works fine when switching between ts and css/less files, and even from html to css/less (alt+i) and from html to ts (alt+u), but switching from ts to html or less to html (alt+o) stopped working for me.  

I'm on visual studio code 1.8.1

**Comment by infinity1207** [comment]
@tomasro27 seems to be a conflict with another extension. i think you should check your vscode's keybindings.
