### ISSUE TITLE
Alt + I doesn't working

### ISSUE THREAD

**Issue by kinanson** [infinity1207/angular2-switcher#9]
I had Alt + I and Alt +U.but I can't use alt+I.I want go to scss file.Can you give me a hand?

**Comment by infinity1207** [comment]
@kinanson seems to be a conflict with another extension. i think you should check your vscode's keybindings.

**Comment by kinanson** [comment]
I am sorry.You are right.I have alt+i go to scss from my mac but I can't use alt +i from my desktop computer.I will check my problem.Thanks.
